version: "3"

volumes:
    db:

services:
  worker: &worker
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    env_file:
      - .env/django
    depends_on:
      - db

  web:
    <<: *worker
    volumes:
      - ./media:/media
      - ./green-medic-backend:/app/green-medic-backend
    command: >
      bash -c "urlwait &&
      ./manage.py migrate &&
      ./manage.py runserver 0.0.0.0:8000"

    ports:
      - "8000:8000"
    restart: always

  db:
    image: postgres:12
    env_file:
      - .env/postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data/pgdata
