# Generated by Django 3.1.1 on 2020-09-30 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopkeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='%(class)s_created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='%(class)s_updated_at')),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=30)),
                ('shop_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('long', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('registration_number', models.CharField(blank=True, max_length=30, null=True)),
                ('nid', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Disabled')], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='%(class)s_created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='%(class)s_updated_at')),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=30)),
                ('age', models.PositiveSmallIntegerField(default=0)),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other'), (4, 'Unspecified')], default=4)),
                ('lat', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('long', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
