# Generated by Django 3.1.1 on 2020-09-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='firebase_uid',
            field=models.CharField(default='te', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopkeeper',
            name='firebase_uid',
            field=models.CharField(default='te', max_length=255),
            preserve_default=False,
        ),
    ]
