# Generated by Django 3.1.1 on 2020-09-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='customer',
            name='long',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
