# Generated by Django 3.1.1 on 2020-09-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200930_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
