# Generated by Django 3.1.1 on 2020-09-28 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20200928_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopkeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='%(class)s_created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='%(class)s_updated_at')),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=30)),
                ('shop_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('long', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('registration_number', models.CharField(blank=True, max_length=30, null=True)),
                ('nid', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
