# Generated by Django 3.1.1 on 2020-09-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_shopkeeper'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopkeeper',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Unapproved'), (2, 'Approved'), (3, 'Disabled')], default=1),
        ),
    ]
