# Generated by Django 3.1.1 on 2020-10-01 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200930_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='firebase_uid',
        ),
        migrations.RemoveField(
            model_name='shopkeeper',
            name='firebase_uid',
        ),
    ]
