# Generated by Django 3.1.1 on 2020-09-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_shopkeeper_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopkeeper',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Disabled')], default=1),
        ),
    ]
