name: Green Medicine Application

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:10.8
        env:
          POSTGRES_USER: green
          POSTGRES_PASSWORD: green
          POSTGRES_DB: green
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Checkout env repo
      uses: actions/checkout@v2
      with:
        repository: Green-Medic/.env
        # Create a PAT for the desired private repo, Add the PAT to Parent repo's secret key.
        token: ${{ secrets.ENV_REPO_TOKEN }} # `ENV_REPO_TOKEN` is a secret that containing my PAT
        path: .env
    - name: Run migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate
    - name: Lint with flake8
      run: |
        flake8

        # stop the build if there are Python syntax errors or undefined names
        # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
